apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}"
data:
  cloudcluster.conf: |-
    server {
      listen 8080;
      listen [::]:8080;
      server_name _;
      root /app/dist;
      index   index.html index.htm;

      proxy_buffer_size   128k;
      proxy_buffers   4 256k;
      proxy_busy_buffers_size   256k;

       proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
       proxy_set_header Host $http_host;
       proxy_set_header X-Forwarded-Host $server_name;
       proxy_set_header X-Real-IP $remote_addr;
       #proxy_set_header X-Forwarded-Proto $scheme;
       proxy_redirect off;

      location ~ ^(\/app)\/platform(\/[^#].+)$ {
          add_header Cache-Control "max-age=0, no-cache, no-store, must-revalidate";
          add_header Pragma "no-cache";
          return 301 $scheme://$http_host/#/app/platform$2$is_args$args;
      }

      location /media/ {
          add_header Cache-Control "max-age=0, no-cache, no-store, must-revalidate";
          add_header Pragma "no-cache";
          alias /app/cloudcluster_media/;
      }

      location /server/ {
          proxy_pass http://platform-api:8080/;
      }

      location /spec {
          proxy_pass http://platform-api:8080/spec;
      }

      location /static/ {
          add_header Cache-Control "max-age=0, no-cache, no-store, must-revalidate";
          add_header Pragma "no-cache";
          alias /app/static/;
      }

      location /auth {
          proxy_set_header X-Real-IP       $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-Port 443;
          proxy_set_header Host $host;
          proxy_ssl_verify      off;

          proxy_pass https://{{ .Values.keycloakServiceName }}:443;

          proxy_buffer_size          128k;
          proxy_buffers              4 256k;
          proxy_busy_buffers_size    256k;
      }
    }
