apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    env: "{{ .Values.env }}"
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
      env: "{{ .Values.env }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        env: "{{ .Values.env }}"
    spec:
      restartPolicy: Always
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /#/app/login
              port: http
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /#/app/login
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          volumeMounts:
            - mountPath: /app/cloudcluster_media
              name: nfs
            - mountPath: /app/static
              name: nfs
            - mountPath: /etc/nginx/conf.d/
              name: proxyconf
            - mountPath: /app/dist/keycloak.json
              name: vuejs-keycloak
              subPath: keycloak.json
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs
        - name: proxyconf
          configMap:
            name: {{ .Chart.Name }}
        - name: vuejs-keycloak
          secret:
            defaultMode: 420
            secretName: "{{ .Chart.Name }}-keycloak"
