apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    component: proxy
spec:
  selector:
    app: "{{ .Chart.Name }}"
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
  type: "{{ .Values.service.type }}"
