apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <service-name>
  namespace: <service-namespace>
spec:
  dnsNames:
  - <service-name>.<cluster-id>.app.daiteap.com
  issuerRef:
    kind: ClusterIssuer
    name: daiteap-clusterissuer
  secretName: cert-<service-name>