name: Create and publish Docker images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  NAMESPACE: daiteap

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Docker "daiteap-ui" meta
        id: daiteap-ui-meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/daiteap-ui
          tags: |
            latest
            ${{ github.sha }}

      - uses: sigstore/cosign-installer@main

      - name: Write signing key to disk
        run: echo "${{ secrets.SIGNING_SECRET }}" > cosign.key

      - name: Build and push "daiteap-ui"
        id: build_and_push_daiteap_ui
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ steps.daiteap-ui-meta.outputs.tags }}
          labels: ${{ steps.daiteap-ui-meta.outputs.labels }}
      
      - name: Sign "daiteap-ui" image
        run: |
          cosign sign -y --key cosign.key \
          ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/daiteap-ui@${{ steps.build_and_push_daiteap_ui.outputs.digest }}
        env:
          COSIGN_PASSWORD: ${{ secrets.SIGNING_SECRET_PASSWORD }}
    