on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unit tests
        uses: actions/setup-node@v3
        with:
          path: app
          node-version: '12.22.12'
      - name: Install dependencies
        run: npm install
      - name: Run tests
      - run: npm test
